<?php
session_start();
if(!isset($_SESSION['user_name'])){
   header("Location:../Login/");
}
?>

<html>
    <link href='http://fonts.googleapis.com/css?family=Roboto:400italic,400' rel='stylesheet' type='text/css'>
    
    
<head>
    <title>Post ID:
<?php
echo $_GET['id'];
?>
    </title>
    <link rel="stylesheet" type="text/css" href="../mathforum_stylesheet.css"/>
    <link rel="shortcut icon" href="../favicon.ico"/>
    <!--<script type="text/javascript"
        src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
    </script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">
    </script>
    <script type="text/javascript" src="buttons.js"></script>
</head>
    


<body>

<?php
include "../header.php";
?>
    
<main>
<?php

//connect to mysql server MathForum
//defines a mysqli object named $mysqli
include '../connect.php';

//variables defined:
//$postid
//$post_query
//$post_result
//$response_query
//$response_result
include 'vars.php';
include 'functions.php';

ini_set('display_errors', '1');
error_reporting(E_ALL);





//HTML 

$postrow = $post_result->fetch_assoc();

//Subject
echo "<h2 class ='subject'> " . 
    $postrow['post_subject'] . 
    "</h2>";


//Post    
echo "<div class='content' class='post'> 
    <p>".  $postrow['post_content'] .
    "</p>";
response_panel($postrow['user_name'], False,"topreply");
echo "</div>";



//Responses
echo "<h3>Responses:</h3>";

display_responses($response_result, $mysqli, $postid, $_SESSION['user_name'], "reply");
    
?>
    
    
    


                
<!--
<h3>Responses:</h3>
                
<div class="content" class="response">
    <p class="text">No, the ideal \(I\) is generated by the element \(4 \in \mathbb{Z}\). In general, the division algorithm shows why \(\mathbb{Z}\) is a PID.</p> 
    
    <div class="content_footer">
        <span>- Fake Man</span>
        
        <button class="respond">Reply</button>
        <img class="respond" src="down.png"></img>
        <img class="respond" src="up.png"></img>
    </div>


    <div class="content below">
        <p class="text">k</p>
        <div class="content_footer">
        <span>- Fake Smith</span>
        
        <button class="respond">Reply</button>
        <img class="respond" src="down.png"></img>
        <img class="respond" src="up.png"></img>
        </div>
    </div>
    <div class="content below">
        <p class="text">kk</p>
        <div class="content_footer">
        <span>- Fake Man</span>
        
        <button class="respond">Reply</button>
        <img class="respond" src="down.png"></img>
        <img class="respond" src="up.png"></img>
        </div>
    </div>
</div>
                
<div class="content" class="response">
    Hi.  
    <div class="content_footer">
        <span>- Fake Man</span>
        
        <button class="respond reply">Reply</button>
        <img class="respond" src="down.png"></img>
        <img class="respond" src="up.png"></img>
    </div>
    <form class="reply">
    <textarea class="reply content below" rows=10></textarea>
    <div class="reply_footer">
        <button class="respond submit">Submit</button>
        <button class="respond cancel" type="button">Cancel</button>
        </div>
    </form>
</div>
-->
                
                
</main>
</body> 

</html>
